Use "NOTSET" to disable logging instead of 'None'
This is needed because log.setLevel(None) fails with:
> TypeError: Level not an integer or a valid string: None